name: bank_mas_re_write
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.2
  logger: ^1.3.0
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  url_launcher: ^6.1.10
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
